runtime: nodejs12

env_variables:
  GOOGLE_CLOUD_PROJECT: YOUR_GOOGLE_CLOUD_PROJECT
  GOOGLE_APPLICATION_CREDENTIALS: YOUR_GOOGLE_APPLICATION_CREDENTIALS
  GCLOUD_STORAGE_BUCKET: YOUR_GCLOUD_STORAGE_BUCKET
  SQL_USER: YOUR_SQL_USER
  SQL_PASSWORD: YOUR_SQL_PASSWORD
  SQL_DATABASE: YOUR_SQL_DATABASE
  INSTANCE_CONNECTION_NAME: YOUR_INSTANCE_CONNECTION_NAME